name: Test SSH Connection to VPS

on:
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository (optional for this test)
      - name: Checkout Code
        uses: actions/checkout@v3

      # Test SSH connection to the VPS
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Connection successful"
            uptime
            ls -al
